org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8 -Drobolectric.dependency.repo.url=https://maven-central.storage-download.googleapis.com/maven2
systemProp.robolectric.dependency.repo.url=https://maven-central.storage-download.googleapis.com/maven2
org.gradle.configuration-cache=true
android.useAndroidX=true
kotlin.code.style=official
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=false
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=true
android.newDsl=true
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE
