package fr.geoking.arthur.genart

enum class GenartEngineId {
    Particles,
    Pseudo3D,
    SoftShadows,
    Tunnel,
    TonalGeometry,
    Sphere,
    Waves,
    Micro,
    Snow,
    Grass,
    BirdFlock,
    Mountains,
    Aurora,
    PondRipples,
    FallingLeaves,
    BreathCircles,
    FireEmbers,
    Dunes,
    Constellation,
    Clouds,
    Rain,
    Fog,
    FishSchool,
    Fireflies,
    Sunbeams,
    Meteors,
    Bubbles,
    CherryBlossoms,
    SoftRibbons,
    Nebula,
    MorphingBlobs,
    SoftNoiseField,
    VoronoiWash,
    SilkFolds,
    GradientMesh,
    ArcMosaic,
    Storm,
    StarField,
    SolarSystem,
    CandleEmber,
    Rainbow,
    Smog,
    Smoke,
    HeatHaze,
    Sunshine,
    LightDrizzle,
    SteamCurl,
    DriftingPollen,
    LandslideDust,
    PebbleShoreWash,
    FrostCrystals,
    IonTrail,
    AntTrails,
    SleepingPet,
    WarpStreak,
    SpaceStationDrift,
    MoonlightRipples,
    EclipseCorona,
    InkInWater,
    WindChime,
    DayNightWash,
    TumbleweedDrift,
    CityLights,
    MossGrowth,
    TerrariumDrip,
    Aquarium,
    Fields,
    RainOnGlass,
    Reeds,
    CanyonDunes,
    Continents,
    Roads,
    Rivers,
    Tree,
    Flower,
    Lake,
    Asteroids,
    WaterfallMist,
    SoftWindStreaks,
    GerstnerOcean,
    SpiralGalaxy,
    DataHorizon,
    SoftCaustics,
    LowFreqNoiseField,
    Fire,
    ChromaticBlobs,
    PrismaticShadows,
    AuroraWash,
    VortexGlow,
    SpectralFolds,
    HaloEclipse,
    PaperCutPack,
    DiamondWeave,
    Matrix,
    DriftingHalos,
    Superdrive,
    Fireworks,
    AtmosphericAsteroid,
    SaturnRings,
    LavaSun,
    Moon,
    SpiralMandala,
    FlowRibbons,
    CliffordWash,
    PlasmaNova,
    EnergyTendrils,
    InterferenceWash,
    NestedPack,
    SilkBloom,
    CrossingSpotlights,
    LampInDarkness,
    BillowingCloth,
    WindCurtains,
    GlassMarbles,
    PaneReflections,
    MarbleCaustics,
    MarbleDrift,
    CanyonLight,
    DepthShafts,
    GlassOrb,
    SoftRayOrbs,
    PrismCave,
    SoapFilm,
    LitLattice,
}

enum class GenartQuality { Low, Medium, High }

data class GenartCatalogEntry(
    val engine: GenartEngineId,
    val id: String,
    val title: String,
)

/**
 * Stable ids/titles for Content Engine Source mapping.
 *
 * Backed by [GenartRegistry] — the single place a new engine gets registered (live Composable +
 * baked still) instead of a separate `when` dispatch per renderer.
 */
object GenartCatalog {
    fun entries(): List<GenartCatalogEntry> = GenartRegistry.catalogEntries()

    fun engineForId(id: String): GenartEngineId? = GenartRegistry.engineForId(id)
}
